// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./TextBox")),
  features: dynamic(() => import("./Dashboard")),
  hero: dynamic(() => import("./DoubleCard")),
  image: dynamic(() => import("./Image")),
};
